spring:
  application:
    name: skilline-server
  datasource:
    url: jdbc:mysql://localhost:6000/skiline?createDatabaseIfNotExist=true
    username: tranquocdat
    password: tranquocdat
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false
#    mongodb:
#      uri: mongodb://root:root@localhost:27017/Chat-service?auth=admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


jwt:
  expirationAccess: 86400
  expirationRefresh: 1296000
  secretKeyAccess: LuNVqXkIK/leKNt+xBkwXK+K25U9cFa2E6v735ZSOQuEIF3B2bvwpEd9UDXiXsZ9SLC1kh4MyTaAxU6Vnq+NeQ==
  secretKeyRefresh: 5bh77qh5vEfCrE3gkrPenjdd5tkk0zmKnz1cDNpIc4w=

url:
  verify-account: http://localhost:8080/auth

mailjet:
  api-key: ${MAILJET_KEY:61a7d3173515fb84be6d8a2c6ce433fe}
  api-secretKey: ${MAILJET_SECRET:470eeb057bc489f636bbe96ee0b952aa}

upload:
  directory:
    video: uploads/lecture
    hls: uploads/hls
    image: uploads/image
    pdf: uploads/pdf

domain:
  server: http://localhost:8080/
  client: http://localhost:8081

